name: Schedule a commit

on:
  schedule:
    - cron: '15 4,8,15 * * 0-2'
    - cron: '0 8-20 * * 1-5'
    - cron: '10 3-11 4-20 * *'

jobs:
  auto_commit:
    name: 'Auto push a commit to report.txt'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create sample file with just timestamp
        run: echo %time% >> report.txt
      - name: Commit file
        run: |
          git config --global user.name 'thanhdang198'
          git config --global user.email 'thanhdang198@users.noreply.github.com'
          git add report.txt
          current_time=$(date +"%Y-%m-%d %H:%M:%S")
          git commit -m "Automated report at $current_time"
          git push
